---
- hosts: tomcat_servers
  become: yes
  tasks:
    - name: Stop Tomcat
      service: name=tomcat state=stopped
      
    - name: Copy ALL WAR files
      copy:
        src: "{{ playbook_dir }}/wars/{{ item }}"
        dest: /opt/tomcat9/webapps/{{ item | regex_replace('.war$', '') }}.war
        owner: tomcat
        group: tomcat
        mode: 0644
      with_items:
        - supermarket.war
        - TestServerKrishna.war
        - sample.war
        
    - name: Start Tomcat
      service: name=tomcat state=started enabled=yes
i
